name: build
on: [push]

jobs:
  gcc-release:
    name: GCC Release
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker
        run: docker build -t test .
      - name: Build code
        run:docker run test:latest
  gcc-debug:
    name: GCC Debug
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker
        run: docker build -t test --build-arg BUILD=Debug .
      - name: Build code
        run:docker run test:latest
  clang-release:
    name: CLang Release
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker
        run: docker build -t test --build-arg --build-arg COMPILER=clang++ .
      - name: Build code
        run:docker run test:latest
  clang-debug:
    name: CLang Debug
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker
        run: docker build -t test --build-arg --build-arg COMPILER=clang++ BUILD=Debug .
      - name: Build code
        run:docker run test:latest
