name: build
on: [push]

jobs:
  gcc-release:
    name: GCC Release
    runs-on: ubuntu-latest
    steps:
      - name: PWD
        run: pwd && ls
      - name: Build Docker
        run: docker build -t test .
      - name: Build code
        run: docker run test:latest
