name: build
on: [push]

jobs:
  gcc-release:
    name: GCC Release
    runs-on: ubuntu-latest
    steps:
      - name: wget
        run: wget https://raw.githubusercontent.com/wow2006/GraphicsDemos/actions/Dockerfile && wget https://raw.githubusercontent.com/wow2006/GraphicsDemos/actions/remove-cmake.patch
      - name: List
        run: ls
      - name: Build Docker
        run: docker build -t test .
      - name: Build code
        run: docker run test:latest
