name: CLang
on: [push]

jobs:
  clang-release:
    name: CLang Release
    runs-on: ubuntu-latest
    steps:
      - name: wget
        run: wget https://raw.githubusercontent.com/wow2006/GraphicsDemos/master/Dockerfile
      - name: Build Docker
        run: docker build -t test --build-arg COMPILER=clang++ .
      - name: Build code
        run: docker run test:latest
  clang-debug:
    name: CLang Debug
    runs-on: ubuntu-latest
    steps:
      - name: wget
        run: wget https://raw.githubusercontent.com/wow2006/GraphicsDemos/master/Dockerfile
      - name: Build Docker
        run: docker build -t test --build-arg COMPILER=clang++ --build-arg BUILD=Debug .
      - name: Build code
        run: docker run test:latest

